### PR TITLE
build CCL for both gsl 2.6 and 2.7

### PR DESCRIPTION
**Pull request by heather999**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

As discussed on LSSTC Slack, we want to support building CCL against both GSL 2.6 and 2.7 while waiting for resolution on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1700

Not certain if I should bump the build number or not, so I haven't touched it yet.

I re-rendered locally just to see that it worked, but didn't commit it.  Instead, I'll insert `@conda-forge-admin please rerender` in a comment below.

### CODE REVIEW

**Comment by heather999** [comment]
@conda-forge-admin please rerender

**Comment by beckermr** [comment]
We can merge this, but I kicked off the gsl2.7 migration, so if we wait for that, this PR would not be needed. Up to you!

**Comment by beckermr** [comment]
The bot should issue a PR by this evening.

**Comment by heather999** [comment]
I'm happy to wait and see if that gsl 2.7 migration finishes up by the end of the week. If you think it might take longer than that - I'd vote to proceed!

**Pull request closed without merging**
